In [ ]:
#Numpy means numerical python,which is used for mathematical and scientific computation.
#mean,variance,standard deviation,median,mode,percentile,quartile in sab ko caculate karne ke liye numpy use hota hai.
#It has a function for working in domain of linear algebra, fourier transform and matrices.

#Numpy uses less memory to store data.Numpy makes it easy to perform mathematical operations on arrays 
#and used for creation of n-dimensional arrays and finding element numpy array is easy.

#pip install numpy

In [8]:
#example of list
l1=[1,2,3,4,5]
l2=[6,7,8,9,10]
print(l1+l2) #output=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
# print(l1*l2) #error
print(l1*10) #output=l1 ko 10 times print kar dega

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [ ]:
#But array me addition,multiply and caluculation easy ho jata h.
import numpy as np
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])
print(a+10) # output=[11 12 13 14 15]
print(b*10)  #output=[60 70 80 90 100]
print(a*b) #output=[ 6 14 24 36 50]
#Note:array me ek hi DataType ka data store hota h.

#array vs list
#array takes less memory
#array can handle direct mathematical calculation
#easier to add,delete element from array
#array me diffent size ka nested data nhi store kar sakte h,but list me store kar sakte h.
l1=[[1,2,3],[4,5]] #output:  [1, 2, 3, [4, 5]]
print(l1)  
# a1=np.array([[1,2,3],[4,5]]) #error
#array me agar first row me 3 element h to second row me bhi 3 element hona chahiye.

[11 12 13 14 15]
[ 60  70  80  90 100]
[ 6 14 24 36 50]
[1, 2, 3, [4, 5]]


In [26]:
#creating arrays in numpy
a1=np.array([1,2,3,4,5]) #1D array
a2=np.array([[1,2,3],[4,5,6]]) #2D array
# print(a1)
# print(a2)

# #slicing of numpy array
print(a1[0:3]) #output=[1 2 3] #0th index se 2rd index tak print karega.(i,e 1st 3 element)
print(a2[0:2,0:2]) #output=[[1 2] [4 5 6]] #0th row se 1st row tak and 0th column se 1st column tak print karega.
#2D array me jitna 1st array me element h utna hi 2nd array me element hona chahiye.
#2D array me hum yesa nhi kar sakte.(print(a2[0:2,0:3])  )

print(a2[1,0:2]) #output [4,5] #1st index pe jo array hai uska 0th index se 1st index tak print karega.

print(a1[-2:])  #last 2 index , [4,5]

print(np.shape(a2)) #output-> (2,3) #2 rows and 3 columns
print(np.size(a2)) #total element in array is 6
print(np.ndim(a2)) #output-> 2 #  2D array
print(a2.dtype) #int64 #dataType of array is INT
print(a1[2:]) #index 2 se last index tak ( [3,4,5] )



[4 5]


In [45]:
#Inspecting an array (array ka size ,shape ,dimensionsand data type pata karne ke liye)
#array_name.shape->(rows,columns)
#len(array_name)->size of  array
#array_name.ndim->dimension of array(1D,2D..)
#array_name.dtype->data type of array 
#array_name.size->total element in array
#array_name.astype(int)->convert to int datatype ..(int,float,str)

import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]]) 
arr.shape #(2,5)
len(arr) #2
arr.ndim #2
arr.dtype #dtype('int64')
arr.size #10(total 10 element)
arr.astype(str)   # array([['1', '2', '3', '4', '5'],
                #  ['6', '7', '8', '9', '10']], dtype='<U21')

array([['1.0', '2.2', '3.0', '4.0', '5.0'],
       ['6.0', '7.0', '8.0', '9.0', '10.0']], dtype='<U32')

In [65]:
#Mathematical operation and Functions on Array
# a1=[1,2,3,4,5] and a2=[6,7,8,9,10] agar array yesa hua to hume proper add,subtract likhna hoga 
#np.add(arr1,arr2)->addition of two array
#np.subtract(arr1,arr2)->subtraction of two array
#np.multiply(arr1,arr2)->multiplication of two array
#np.divide(arr1,arr2)->division of two array

#agar np.array() ke help se array banayenge to direct +,-,*,/ use kar sakte h.
a1=np.array([1,2,3,4,5])
a2=np.array([9,7,8,6,10])
print(a1+a2)
print(a1-a2)
print(a1/a2)
print(a1*a2)
print(a2%a1)
print(a1**2) #square of each element
print(a1**a2) #a1 power a2  (1^9,2^7,3^8,4^6,5^10 )


[10  9 11 10 15]
[-8 -5 -5 -2 -5]
[0.11111111 0.28571429 0.375      0.66666667 0.5       ]
[ 9 14 24 24 50]
[0 1 2 2 0]
[ 1  4  9 16 25]
[      1     128    6561    4096 9765625]


In [2]:
#combining and splitting array
import numpy as np
a=np.array([3,4,5])
b=np.array([1,2,3])

#concatenate array
print(np.concatenate((a,b))) #output=[3 4 5 1 2 3]

#2D array
c=np.array([[3,4,5],[6,7,8]])
d=np.array([[1,2,3],[10,11,12]])
print(np.concatenate((c,d),axis=1)) #  [[ 3  4  5  1  2  3]  #print(np.hstack((c,d)))  ->same output
                                    #  [ 6  7  8 10 11 12]]

print(np.concatenate((c,d),axis=0))  #[[ 3  4  5]   #print(np.vstack((c,d))) ->same output
                                    #  [ 6  7  8]
                                    #  [ 1  2  3]
                                    #  [10 11 12]]


#splitting array                        
print(np.array_split(a,3)) #output=[array([3]), array([4]), array([5])] #array ko 3 parts me split kro
y=np.array_split(b,2)
print(y)  #[array([1, 2]), array([3])]
print(y[0]) #[1 2]  , y[0] ->access first array(i.e,0th index)
print(y[1]) # [3]

[3 4 5 1 2 3]
[[ 3  4  5  1  2  3]
 [ 6  7  8 10 11 12]]
[[ 3  4  5]
 [ 6  7  8]
 [ 1  2  3]
 [10 11 12]]
[array([3]), array([4]), array([5])]
[array([1, 2]), array([3])]
[1 2]
[3]


In [33]:
#Adding and Removing element from array
#np.append(array_name,element)->add element at the end of array
#np.insert(array_name,index,element)->add element at specific index
#np.delete(array_name,index)->delete element at specific index

import numpy as np
arr=np.array([1,12,3,4,5])

#method 1->
print(np.append(arr,7) )  #[1 12 3 4 5 7]
print(arr) #[1 12 3 4 5]
print(np.insert(arr,2,9)) #[1 12 9 3 4 5]
print(arr) #[1 12 3 4 5]

# Note->append and insert karne ke baad jo original array tha usme koi changes nhi aaya h,
#      agar mujhe origin array me changes chahiye to,
#method 2->
arr=np.append(arr,7)
print(arr) #[1 12 3 4 5 7]
arr=np.insert(arr,2,9)
print(arr) #[1 12 9 3 4 5 7]

#Insert in 2D array
arr2=np.array([[1,12,3,4,5],
                [6,7,8,9,10]])
print(np.append(arr2,[16,19,20]) )
print(arr2)
print(np.insert(arr2,1,[28,39],axis=1))

[ 1 12  3  4  5  7]
[ 1 12  3  4  5]
[ 1 12  9  3  4  5]
[ 1 12  3  4  5]
[ 1 12  3  4  5  7]
[ 1 12  9  3  4  5  7]
[ 1 12  3  4  5  6  7  8  9 10 16 19 20]
[[ 1 12  3  4  5]
 [ 6  7  8  9 10]]
[[ 1 28 12  3  4  5]
 [ 6 39  7  8  9 10]]


In [42]:
#sort ,filter and search in array
#np.sort(array_name)->sort array
#np.where(array_name>value)->search element in array
#np.searchsorted(array_name,value)->search element in array
#np.filter(array_name,condition)->filter element in array
import numpy as np
arr=np.array([1,12,3,4,5])
sorting=np.sort(arr) 
print(sorting) #[ 1  3  4  5 12]
searching=np.where(arr==4) 
print(searching) #( array[3] )   it return index position, (4 jo hai uska index 3 hai)

filtered_arr = arr[arr > 4]
print(filtered_arr)  #[12  5]  

[ 1  3  4  5 12]
(array([3]),)
[12  5]


In [57]:
#Aggregation function in numpy
import numpy as np
a=np.array([20,30,50,70,90])
print("sum=",np.sum(a)) #260
print("min=",np.min(a)) #20
print("max=",np.max(a)) #90
print("number of elements in array=",np.size(a)) #5
print("mean=",np.mean(a)) #52.0
print("median=",np.median(a)) #50.0
print("50 percentile=",np.percentile(a,50)) #50.0
print("25 percentile=",np.percentile(a,25)) #25.0
print("75 percentile=",np.percentile(a,75)) #70.0  #75 percentile
print("variance=",np.var(a)) #600.0          #variance
print("standard deviation=",np.std(a)) #24.494897427814228 #standard deviation
print("cummulative sum=" ,np.cumsum(a)) #current element se piche tak ka sum
print("cummulative product=",np.cumprod(a)) #current element se piche tak ka product

#example 1
price=np.array([20,30,50,70,90])
quantity=np.array([10,12,30,40,50])

print(np.cumprod([price,quantity],axis=0)) #output= [[  20   30   50   70   90]
                                                #   [ 200  360 1500 2800 4500]]
print(np.cumprod([price,quantity],axis=1)) #output= [[ 20  600  30000  2100000  189000000]
                                              #     [ 10  120  3600   144000    7200000]]


sum= 260
min= 20
max= 90
number of elements in array= 5
mean= 52.0
median= 50.0
50 percentile= 50.0
25 percentile= 30.0
75 percentile= 70.0
variance= 656.0
standard deviation= 25.612496949731394
cummulative sum= [ 20  50 100 170 260]
cummulative product= [       20       600     30000   2100000 189000000]
[[  20   30   50   70   90]
 [ 200  360 1500 2800 4500]]
[[       20       600     30000   2100000 189000000]
 [       10       120      3600    144000   7200000]]
